export default () => ({
  hotels: null,
  // Below is a simulation of how an endpoint's data would come to list the hotels in the chosen city
  // this state would be set through a mutation that would be called by an action where a get request would be made. just like "hotels" above
  hotelsList: [
    {
      hotelName: 'Belmond Grand Hotel',
      hotelStatus: 5,
      hotelType: 'resort',
      price: 'U$ 2.500,00',
      image: '/images/belmond-sm.jpg',
      hotelFeatures: {
        internet: true,
        park: true,
        outsidePool: true,
        pool: true,
        gym: true,
        reception: true,
        restaurant: false,
        bar: false,
        air: false,
        animalsAllowed: false,
      },
    },
    {
      hotelName: 'Four Seasons',
      hotelStatus: 5,
      hotelType: 'hotel',
      price: 'U$ 2.000,00',
      image: '/images/fourseasons-sm.jpg',
      hotelFeatures: {
        internet: true,
        park: true,
        outsidePool: false,
        pool: true,
        gym: true,
        reception: false,
        restaurant: true,
        bar: true,
        air: false,
        animalsAllowed: false,
      },
    },
    {
      hotelName: 'Fairmont Hotel & Resort',
      hotelStatus: 5,
      hotelType: 'Resort',
      price: 'U$ 1.800,00',
      image: '/images/fairmont-sm.jpg',
      hotelFeatures: {
        internet: true,
        park: true,
        outsidePool: true,
        pool: false,
        gym: true,
        reception: false,
        restaurant: true,
        bar: true,
        air: false,
        animalsAllowed: false,
      },
    },
    {
      hotelName: 'Mandarin Hotel',
      hotelStatus: 4,
      hotelType: 'hotel',
      price: 'U$ 850,00',
      image: '/images/mandarin-sm.jpg',
      hotelFeatures: {
        internet: true,
        park: true,
        outsidePool: true,
        pool: false,
        gym: true,
        reception: true,
        restaurant: false,
        bar: false,
        air: true,
        animalsAllowed: false,
      },
    },
    {
      hotelName: 'Holiday inn Hotel',
      hotelStatus: 3,
      hotelType: 'hotel',
      price: 'U$ 150,00',
      image: '/images/holiday-sm.jpg',
      hotelFeatures: {
        internet: true,
        park: false,
        outsidePool: false,
        pool: true,
        gym: true,
        reception: true,
        restaurant: false,
        bar: false,
        air: true,
        animalsAllowed: true,
      },
    },
    {
      hotelName: 'Ibis Budget',
      hotelStatus: 2,
      hotelType: 'hotel',
      price: 'U$ 80,00',
      image: '/images/ibis-sm.jpg',
      hotelFeatures: {
        internet: true,
        park: true,
        outsidePool: false,
        pool: false,
        gym: true,
        reception: true,
        restaurant: false,
        bar: false,
        air: false,
        animalsAllowed: false,
      },
    },
  ],
  citySelected: null,
})
